version: '3'
    
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  migration:
    build: .
    command: python manage.py migrate --noinput
    env_file:
      - docker-postgres.env
    volumes:
      - .:/code
    depends_on:
      - db
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - docker-postgres.env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - migration
      - db
