# Generated by Django 3.0.7 on 2020-06-16 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_observation_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='published_date',
        ),
    ]
