# Generated by Django 3.0.6 on 2020-06-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_auto_20200616_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='obs_client',
            field=models.ManyToManyField(help_text='Hold down "Control", or "Command" on a Mac, to select more than one.', to='survey.Observation_Individual'),
        ),
    ]
