# Generated by Django 3.0.6 on 2020-06-30 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_enums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_client',
            field=models.ManyToManyField(help_text='Hold down "Control", or "Command" on a Mac, to select more than one.', to='survey.Survey_Individual'),
        ),
    ]
