# Generated by Django 3.0.6 on 2020-07-24 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('survey', '0009_auto_20200629_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='observation_individual',
            name='c_obs_user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
